import { Card, Icon, Modal, Text } from '@ui-kitten/components';
import React, { FunctionComponent, useState } from 'react';
import { TouchableOpacity } from 'react-native-gesture-handler';
import BigButton from '../../common/BigButton';
import getThemeVars from '../../common/getThemeVars';

const UnverifiedMessageIndicator: FunctionComponent = () => {
  const { alertColor } = getThemeVars();
  const [isUnverifiedModalOpen, setIsUnverifiedModalOpen] = useState(false);

  return (
    <>
      <Modal
        visible={isUnverifiedModalOpen}
        backdropStyle={{
          backgroundColor: 'rgba(0, 0, 0, 0.5)',
        }}
        onBackdropPress={() => setIsUnverifiedModalOpen(false)}
      >
        <Card disabled={true} style={{ maxWidth: 400 }}>
          <Text category="h2" style={{ marginBottom: 16 }}>
            What is an Unverified Message?
          </Text>
          <Text style={{ marginBottom: 16 }}>
            {`To keep you safe from malicious participants that would modify your messages claiming to be you, Liqid Chat generates a signed credential to confirm that a message was actually made by you. If a message has the "Unverified Message" indicator, it means that Liqid Chat's signed credential is either not present on that message, or it is invalid in some way.`}
          </Text>
          <Text style={{ marginBottom: 16 }}>
            {`Not all "Unverified Messages" are the result of a malicious actor. If they were generated by a chat client that does not create signed credentials or they were modified by the original creator in the Pod, the message will be considered unverified.`}
          </Text>
          <BigButton
            title="Okay"
            onPress={() => setIsUnverifiedModalOpen(false)}
          />
        </Card>
      </Modal>
      <TouchableOpacity
        style={{
          flexDirection: 'row',
          alignItems: 'center',
          paddingBottom: 4,
        }}
        onPress={() => setIsUnverifiedModalOpen(true)}
      >
        <Icon
          name="alert-circle-outline"
          fill={alertColor}
          style={{ width: 16, height: 16, marginRight: 4 }}
        />
        <Text style={{ color: alertColor, textDecorationLine: 'underline' }}>
          Unverified Message
        </Text>
        <Icon
          name="question-mark-circle-outline"
          fill={alertColor}
          style={{ width: 16, height: 16, marginLeft: 4 }}
        />
      </TouchableOpacity>
    </>
  );
};

export default UnverifiedMessageIndicator;
